# Generated by Django 4.2.5 on 2023-09-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.squad')),
            ],
        ),
    ]
