# Generated by Django 4.2.5 on 2023-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
