# Generated by Django 4.2.5 on 2023-09-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_host_hostname_alter_host_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
