# Generated by Django 4.2.5 on 2023-09-28 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_host_check_date_host_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='check_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
